media:
  input: public
  output: /
content:
  - name: posts
    label: Posts
    type: collection
    path: src/content/blog
    view:
      fields: [ title, description, draft, date ]
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: draft, label: Draft, type: boolean }
      - { name: description, label: Description, type: string }
      - { name: date, label: Date, type: date }
      - { name: body, label: Body, type: rich-text }
