content:
  - name: posts
    label: Posts
    path: src/content/blog
    type: collection
    fields:
      - {name:title, label:Title, type:string}
      - {name:description, label: Description, type:string, options: {maxlength:160}}
      - {name:date, label:Date, type:date}
      - {name:draft, label:Draft, type:boolean, default:false}
